wordBoostList = [
"Dalton Sakthivadivel",
"Thomas Parr",
"Lagrange",
"Lagrangian",
"centripetal force",
"centripetal",
"Jorge Esteves",
"Zoe McParlin",
"Francesco Cerritelli",
"Beren Millidge",
"Anil Seth",
"Christopher L Buckley",
"Chris Buckley",
"Axel Constant",
"Andy Clark",
"Michael Kirchhoff",
"Lancelot Costa",
"Axel Constant",
"Andy Clark",
"Michael Kirchhoff",
"Tim Verbelen",
"Toon Van de Maele",
"Bart Dhoedt",
"Adam Safron",
"Tim Verbelen",
"Toon Van de Maele",
"Bart Dhoedt",
"Adam Safron",
"Verbelen",
#
"ActInf Lab GuestStream",
"ActInf Lab Livestream",
"ActInf Lab MathStream",
"ActInf Lab ModelStream",
"ActInf Lab OrgStream",
"ActInf Lab project",
"ActInf Livestream",
"ActInf",
"ActInfLab project",
"Active Inference",
"Active Inference GuestStream",
"Active Inference Institute",
"Active Inference Lab",
"Active Inference Livestream",
"Active Inference MathStream",
"Active Inference ModelStream",
"Active Inference OrgStream",
"Bayesian",
"Bayesian inference",
"Bleu",
"Daniel",
"Dean",
"Dot One",
"Dot Two",
"Dot Zero",
"Free Energy Principle",
"Friston",
"Friston blanket",
"Karl Friston",
"Karl J. Friston",
"Livestream Number",
"Markov",
"Markov blanket",
"Markov decision",
"Stephen",
"YouTube",
# -----------------
"radial parameterisation",
"tangential forces",
"parameterisation",
"tangential",
"Principle of Least Action",
"Least Action",
"Aaron Fath",
"Aaron J Fath",
"Abbas Edalat",
"accuracy",
"ActInf Lab",
"action oriented representation",
"action planning",
"action prediction",
"action",
"active states",
"active",
"activity",
"Adam Linson",
"Adam Safron",
"Safron",
"adaptive",
"address",
"Adeel Razi",
"advantage function",
"affect",
"affordance",
"agency",
"agent",
"agreement",
"Aikaterini Fotopoulou",
"Alessandra Pedrocchi",
"Alex Kiefer",
"Alexander Strobel",
"align",
"allostasis",
"allostat",
"ambiguity",
"Amir Omidvarnia",
"ancestral",
"Andrea Gajardo Vidal",
"Andreas Kleinschmidt",
"Andrew Corcoran",
"Andrew W Corcoran",
"Anna Belardinelli",
"Annemie Ploeger",
"Anthony Chen",
"Anthony G Chen",
"Anthony Zador",
"and",
"ants",
"ant",
"anxiety",
"architectures",
"Ari E Kahn",
"Ari Kahn",
"Arnold Pfeffer",
"aspects",
"assumptions",
"asymmetry",
"attention",
"Attial",
"attributes",
"awareness",
"bacterium like",
"Ballard",
"Bart Dhoedt",
"Bayesian statistics physics",
"behavior",
"belief updating",
"belief",
"beliefs",
"Bellman equation",
"Bellman",
"Beni",
"Benjamin Illingworth",
"Benucci",
"Bert de Vries",
"Bert de Vries",
"Bijan Khezri",
"Bijan",
"bioelectric",
"biological",
"Biology and Philosophy",
"biology",
"Bitcoin",
"blanket states",
"Blei",
"blueprint",
"bottom up",
"Botvinick",
"boundary",
"brain architecture",
"brain evolution",
"brain",
"Brea",
"Bull",
"Buzsaki",
"Canada",
"canonical",
"capacity curve",
"Carnap",
"Casper Hesp",
"Cathy J Price",
"Cathy Price",
"Chang Kim",
"Chang Sub Kim",
"Chantelle Gaylor",
"Chantelle M Gaylor",
"chaos",
"Charles C H Hong",
"Christian Guckelsberger",
"Christoph Mathys",
"Christoph Salge",
"Christopher D Frith",
"Christopher Frith",
"Christopher Lynn",
"Christopher W Lynn",
"Beren Milledge",
"Anil Seth",
"Calgary",
"Chance",
"Christopher L. Buckley",
"Claudia Clopath",
"Clopath",
"Coda",
"cognition",
"cognitive niche",
"cognitive science",
"cognitive scientist",
"cognitive studies",
"cognitive",
"coherence",
"coherent",
"comma",
"communication",
"competition",
"complexity",
"computational",
"computer",
"concept",
"concepts",
"connectivity",
"Conor Heins",
"Conor",
"continuum",
"control error",
"control theory",
"control",
"controlled process",
"controller",
"controls",
"conversation",
"Conway",
"correlation",
"Costa",
"counterfactuals",
"COVID",
"cue",
"culture",
"cybernetics",
"cycle",
"D Maisto",
"DAG",
"DAGs",
"Daniel Polani",
"Daniel Williams",
"Danielle Bassett",
"Danielle de Kerckhove",
"Danielle Kerckhove",
"Danielle S Bassett",
"Daphne Demekas",
"Daphne",
"Dario Cuevas Rivera",
"Dario Cuevas Rivera",
"Dario Rivera",
"data",
"Dauwels",
"David Benrimoh",
"David Benton",
"David Cittern",
"David Green",
"David Krakauer",
"David McKay",
"David W Green",
"Dayan",
"DCM",
"de Vries",
"Declan Lewis",
"Deneve",
"Dennett",
"Diana Morelen",
"differentiate",
"dimension",
"Dimitrije Markovi",
"Dirichlet",
"distinctions",
"disturbance",
"domain",
"Dot EDU",
"Dutch",
"dynamics",
"Earle Jamieson",
"ecological",
"Edda Bilek",
"Edelman",
"Eirik Sovik",
"Elenora Guanziroli",
"emergence",
"Emmanuel Dauce",
"Emmanuel Dauce",
"enactivism",
"encoding",
"endstopping",
"energy",
"English",
"ensemble",
"Ensor Palacios",
"Ensor Rafael Palacios",
"entorhinal",
"environment",
"enzymes",
"epistemic value",
"ergodicity",
"Erik Rietveld",
"errors",
"Ettore Ambrosini",
"evidence",
"evolution",
"Evolutionary Anthropology",
"exafferent",
"examples",
"expectation",
"expected free energy",
"exploration",
"explore",
"external states",
"exteroception",
"Fabienne Picard",
"Fabrice Bartolomei",
"Faisal Mushtaq",
"feedback control",
"feedback",
"Felix A Pollock",
"Felix Pollock",
"Feynman",
"field",
"fitness",
"flagella",
"Florian Ott",
"flow",
"fMRI imaging",
"fMRI",
"force",
"foraging",
"forage",
"forward model",
"framework",
"Francesco Donnarumma",
"Francesco Rigoli",
"Franco Molteni",
"Franz Kuchling",
"Frederike H Petzschner",
"Frederike Petzschner",
"free energy",
"free",
"function",
"gain",
"generalized capacity curve",
"generalized free energy",
"generative model",
"generative models",
"generative process",
"generative",
"Geoffrey Bingham",
"Georgi Georgiev",
"Geraint Rees",
"Gerry Edelman",
"Giovanni Pezzulo",
"Giuseppe Pagnoni",
"goal directed",
"Graeme D Jackson",
"Graeme Jackson",
"Grigorios A Pavliotis",
"Grigorios Pavliotis",
"Guido Hesselmann",
"Hae Jeong Park",
"Hae Park",
"Harrison",
"Hayley A Young",
"Hayley Young",
"Hebbian",
"Helene Haker",
"Helmholtz Decomposition",
"Helmholtzian",
"Helmholtz",
"heuristic",
"hidden states",
"Hideaki",
"hierarchical model",
"hierarchical",
"Hinton",
"Hipolito",
"Hohwy",
"homeostatic",
"homeostat",
"Hugo Bottemanne",
"Brennan",
"Alexander Tschantz",
"Iain Couzin",
"implication",
"inclination",
"independent",
"individual",
"individuals",
"indoctrination",
"Ines Hipolito",
"introduction",
"Francesco",
"Jorge",
"Cerritelli",
"Esteves",
"musculoskeletal",
"Albarracin",
"Andersen",
"Anna Lembke",
"Atreides",
"Azarian",
"Bayesianism",
"Bobby Azarian",
"Brett",
"Brett Andersen",
"Brett P. Andersen",
"Dalton A R Sakthivadivel",
"Dalton Sakthivadivel",
"David Douglass",
"Dean Tickles",
"Dobson",
"Facchin",
"Giovanni",
"Giovanni Rolla",
"John Vervaeke",
"Julian",
"Julian Kiverstein",
"Kiverstein",
"Kyrtin",
"Alessandro Barp",
"Guilherme Franca",
"Mark Girolami",
"Alessandro",
"Barp",
"Guilherme","Franca",
"Girolami",
"Michael Jordan",
"Kyrtin Atreides",
"Lembke",
"Mahault",
"Marco",
"Marco Facchin",
"Proksch",
"Ramstead",
"Ronen",
"Ronen Tamari",
"Shanna",
"Shanna Dobson",
"Shannon Proksch",
"Stephen Sillett",
"Tamari",
"Vervaeke",
"William Fischer",
"Monod",
"epistemic",
"literalist",
"instrumentalism",
"literalist fallacy",
"deflationary account",
"deflationary",
"vehicle externalism",
"externalism",
"schizotypy",
"diametric",
"stigmergic social annotation",
"collective sensemaking",
"sensemaking",
"stigmergic",
"social annotation",
"annotation",
"Shahaf",
"radically enactive cognition",
"radically enactive",
"Gibsonian",
"dialetheia",
"Deleuze",
"condensed object",
"haecceity",
"Grothendieck",
"governance",
"Ines",
"inference",
"influence",
"information geometry",
"information",
"informational",
"interactions",
"interface",
"internal model",
"internal representation",
"internal states",
"interoception",
"interoceptive",
"interpretation",
"inverse model",
"Isomura",
"Jablonka",
"Jack Brookes",
"Jakob Hohwy",
"Jakub Limanowski",
"Jakub Smekal",
"Jakub",
"James C Harris",
"James Cooke",
"James E Cooke",
"James E Swain",
"James Fallon",
"James H Fallon",
"James Harris",
"James Swain",
"James Whittington",
"Tolman Eichenbaum Machine",
"Javier Sanchez Canizares",
"Jean Decety",
"Jelle Bruineberg",
"Jelle",
"Jiyoung Kang",
"Johannes Lohmann",
"John Doherty",
"John O Doherty",
"Jonathan P Roiser",
"Jonathan Roiser",
"Judea Pearl",
"Jun Tani",
"Justyna Ekert",
"Justyna O Ekert",
"Kai Ueltzhoffer",
"Kant",
"Kappel",
"Karl J Friston",
"Karl",
"Katherine L Rosenblum",
"Katherine Rosenblum",
"Khezri",
"Kilner",
"Kirchhoff",
"Klaas E Stephan",
"Klaas Stephan",
"Kuchling",
"Kuhn",
"Laje",
"Lamme",
"Lancelot",
"language",
"Lars Muckli",
"Laurence J Kirmayer",
"Laurence Kirmayer",
"Laurent Perrinet",
"learning",
"least action",
"least",
"leave it to",
"leave to",
"left it to",
"left to",
"Leipzig",
"levels",
"Lieke de Boer",
"Lilian A E Weber",
"linguistics department",
"Linsker",
"Lisa Barrett",
"Lisa Feldman Barrett",
"living system",
"local",
"Lorenzo Niero",
"loss function",
"Lyapunov",
"M Berk Mirza",
"M Mirza",
"macaque",
"Maell Cullen",
"Mahault Albarracin",
"Majid Beni",
"Majid D Beni",
"Majid",
"Mangor Pedersen",
"Manuel Baltieri",
"Marc Tittgemeyer",
"Marcello Costantini",
"Maria Muzik",
"Mark Mon Williams",
"Mark Solms",
"Mark Williams",
"Markov decision process",
"Marolla",
"Marta Gandolla",
"Martin Biehl",
"Martin Butz",
"Martin V Butz",
"Martin Voss",
"match.com",
"material",
"maths",
"MATLAB",
"Matthew M Nour",
"Matthew Nour",
"Mattia Veronese",
"Max Planck",
"Maxwell J D Ramstead",
"Maxwell Ramstead",
"maze",
"measurement noise",
"measurement",
"membrane",
"mesoanatomical",
"metacognition",
"Micah Allen",
"Michael Levin",
"Michael Moutoussis",
"Michael Weisberg",
"Michael",
"Mike Levin",
"Milledge",
"mind",
"minimization",
"minimizing",
"model based",
"model selection",
"model",
"modelers",
"modularity",
"Moser",
"multimodal expansion",
"multimodal",
"multiple",
"narrative",
"Nathaniel Nyema",
"neoplasia",
"neuroimaging",
"neuromodulator",
"niche",
"Nick S Ward",
"Nick Ward",
"noise",
"nonclassical",
"Noor Sajid",
"novelty",
"numbers",
"objective function",
"observation",
"Oliver D Howes",
"Oliver Howes",
"Olivier Sigaud",
"Omar Khachouf",
"Omar T Khachouf",
"online",
"ontology",
"operating point",
"operations",
"order",
"OrgStream",
"osteopath",
"osteopathy",
"overload",
"overridable",
"Ozan Catal",
"parse",
"partial",
"participants",
"particle",
"Pasco Fearon",
"Patrice Duquette",
"Patrick Connolly",
"Paul B Badcock",
"Paul Badcock",
"Paul Fletcher",
"Peirce",
"perception",
"performance",
"perspective",
"perturbation",
"Peter Bossaerts",
"Peter Culmer",
"Peter Uhlhaas",
"Peter Vincent",
"Pezzulo",
"phase",
"Philipp Schwartenbeck",
"Philipp Sterzer",
"philosophy",
"phyletic gradualism",
"physics",
"physiological",
"Piaget",
"plant",
"plasticity",
"play",
"policy selection",
"policy",
"polyethism",
"POMDP",
"position",
"possibility",
"posterior",
"pragmatic value",
"pragmatics",
"pragmatism",
"prediction error",
"prediction",
"Predictive Coding",
"predictive processing",
"predictive regulation",
"Predrag Petrovic",
"preference",
"principle",
"prior",
"probabilistic graphical model",
"process noise",
"process theory",
"processes",
"processing",
"professional setting",
"program",
"prompting",
"punctuated equilibrium",
"pymdp",
"conor",
"quantum",
"question",
"questions",
"Quigley",
"radical enactivist",
"Rao and Ballard",
"Raphael Kaplan",
"Raymond Dolan",
"Raymond J Dolan",
"reafferent",
"reality",
"realize",
"recognition model",
"recognition",
"reference distribution",
"reference trajectory",
"reflective",
"refrigerator",
"regime of attention",
"regulated resource",
"relationships",
"representation",
"representational",
"representationalism",
"representations",
"response curve",
"Richard E Rosch",
"Richard M Wilkie",
"Richard Rosch",
"Richard Wilkie",
"Rick A Adams",
"Rick Adams",
"Riemann",
"Robin Carhart Harris",
"Robin Harris",
"role",
"Rosalyn J Moran",
"Rosalyn Moran",
"Ross",
"Roy de Kleijn",
"Roy Kleijn",
"rules",
"Rutger Goekoop",
"Ryan Smith",
"Ryota Kanai",
"S Ho",
"S Shaun Ho",
"Saee Paliwal",
"salience",
"Samarth Swarup",
"Samuel P L Veissiere",
"Samuel Veissiere",
"Sandra Iglesias",
"saturation value",
"scale",
"scenario",
"science",
"section",
"selection",
"Sennesh",
"sense states",
"Sepideh Sadaghiani",
"set point",
"set",
"settling point",
"settling range",
"Shaun Gallagher",
"Shaun Ho",
"Shimazaki",
"Sillett",
"Simon C Smith",
"Simon Smith",
"solenoidal ",
"SPM",
"stability",
"state estimate",
"state space",
"state",
"states",
"stationarity",
"Stefan J Kiebel",
"Stefan Kiebel",
"Stefano Poletti",
"Stephen Fleming",
"Stephen Fox",
"Stephen Lawrie",
"Stephen M Fleming",
"Stephen M Lawrie",
"Stephen Mann",
"Sterling Street",
"stigmergic",
"stigmergy",
"stimuli",
"stochastic optimal control",
"stock",
"structures",
"Sukhi Shergill",
"surprise",
"surround",
"Sussillo",
"synaptic",
"Takazumi Matsumoto",
"Takuya Isomura",
"Takuya",
"Tarik Dahoun",
"Taylor Series",
"Taylor",
"teaching",
"teleology",
"temporal depth",
"theorem",
"theory",
"Theriault",
"thermodynamics of the brain",
"thermodynamics",
"Thomas Goschke",
"Thomas H B FitzGerald",
"Thomas Hope",
"Thomas M Hope",
"Thomas Parr",
"threshold value",
"Tim Gard",
"Tim Verbelen",
"Tim Verbelen",
"time scales",
"Timothy Behrens",
"Tobias Nolte",
"Toon Van de Maele",
"top down",
"Torigoe",
"Toronto",
"transfer function",
"transfer",
"transition",
"truth",
"Turrigiano",
"uncertainty",
"understanding",
"University of Surrey",
"value function",
"variable",
"variational free energy",
"variational",
"vehicles",
"Veissiere",
"viscerosensory signaling",
"viscerosensory",
"vision",
"Vivien Ainley",
"Volterra series",
"Volterra",
"Wael Deredy",
"Wael El Deredy",
"wayfinding",
"Yoshio Nakamura",
"Zador",
"zebra",
"Zhang",
"Zina M Manjaly",
"Zina Manjaly",
#
"I",
"I'll",
"I've",
"I'm"
]